### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by Srinija-TA**
Here I have packaged housing project into house_price_prediction package
# Installation of package
pip install house_price_prediction

### CODE REVIEW

**Comment by Srinija-TA** [comment]
# Testing whether created project is installed in other system
Screenshot 2023-12-14 143248 (1)

**Comment by Srinija-TA** [comment]
# Testing that package is already installed in my system
srinija

**Comment by Srinija-TA** [comment]
# Uploading the project to the Python Package Index
pypi
https://pypi.org/project/house-price-prediction/#files

**Comment by Srinija-TA** [comment]
# Testing the installation
package output

**Comment by Srinija-TA** [comment]
# Zipped folder attachment (python distribution artifacts tar.gz)
[house_price_prediction-0.0.1.tar.zip](https://github.com/Srinija-TA/mle-training/files/13718619/house_price_prediction-0.0.1.tar.zip)
tar.gz and .whl files are in the dist folder

**Comment by Srinija-TA** [comment]
Closes #13

**Review by venky3001 — APPROVED** [review]

**Pull request merged**
